ALTER TABLE "Category" ADD COLUMN IF NOT EXISTS "image" TEXT;

ALTER TABLE "Brand" ADD COLUMN IF NOT EXISTS "country" TEXT;

ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "sku" TEXT,
ADD COLUMN IF NOT EXISTS "sizes" TEXT,
ADD COLUMN IF NOT EXISTS "stockQuantity" INTEGER,
ADD COLUMN IF NOT EXISTS "popular" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "isNew" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "isSale" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Order"
ALTER COLUMN "shippingAddress" DROP NOT NULL,
ALTER COLUMN "paymentMethod" DROP NOT NULL;

ALTER TABLE "Order"
ADD COLUMN IF NOT EXISTS "deliveryType" TEXT,
ADD COLUMN IF NOT EXISTS "comment" TEXT,
ADD COLUMN IF NOT EXISTS "customerFirstName" TEXT,
ADD COLUMN IF NOT EXISTS "customerLastName" TEXT,
ADD COLUMN IF NOT EXISTS "customerPhone" TEXT,
ADD COLUMN IF NOT EXISTS "customerEmail" TEXT;

